# each drone will have a static IP so that they could communicate (basically to avoid getting all IPs in the code)
services:
    drone-a:
        container_name: D1
        build:
            dockerfile: src/drone/DockerFile.Drone
        networks: 
            CPS-Network: 
                ipv4_address: 172.20.0.10
    
    drone-b:
        container_name: D2
        build:
            dockerfile: src/drone/DockerFile.Drone
        networks:
            CPS-Network: 
                ipv4_address: 172.20.0.20

networks:  
    CPS-Network: 
        driver: bridge

        ipam: 
            config:
                - subnet: 172.20.0.0/24