FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src/drone/include ./include
COPY src/drone/src ./src
COPY src/drone/main.cpp .

RUN g++ -std=c++20 -I include src/utils.cpp main.cpp  -o main

ENTRYPOINT ["./main"]